format_version = 1

[components.zakura]
repository = "https://github.com/endophysics/zakura.git"
upstream = "https://github.com/zakura-core/zakura.git"
revision = "11b3d9818f42eb8b4d06f6764ec50daaaa46694e"
upstream_base = "a03dac8f6136962f749540919a183c9d182db52b"
path = "../zakura"
required = true

[components.gateway]
path = "../zcash-private-gateway"
required = false

[components.zaino]
path = "../zaino"
required = false

[components.wallet]
path = "../wallet-sdk"
required = false

[components.zebra]
path = "../zebra"
required = false
