#!/usr/bin/env python3

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.privacy_contract_commands import run_policy_validate


raise SystemExit(run_policy_validate(sys.argv[1:]))
